name: Build and tests (ARM)

on:
  # Ignore changes in extra plugins (as they are not tested here)
  push:
    paths-ignore:
      - 'extra_plugins/**'
  pull_request:
    paths-ignore:
      - 'extra_plugins/**'

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    name: Build and run tests on ARM
    steps:
    - uses: actions/checkout@v4
    - name: Build on Ubuntu 24.04
      run: |
        sudo apt-get update
        sudo apt-get -y install git gcc g++ cmake make libxml2-dev liblz4-dev libzstd-dev
        sudo apt-get -y install python3-docutils zlib1g-dev pkg-config
        sudo apt-get -y install librdkafka-dev

        # clone libfds
        git clone --branch master https://github.com/CESNET/libfds.git libfds_build

        # build libfds
        cd libfds_build
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr
        make
        sudo make install
        cd ../..

        # build ipfixcol2
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=1
        make
        sudo make install

        # run ipfixcol2 tests
        make test

        # try to run ipfixcol2
        ipfixcol2 -V
        ipfixcol2 -h
        ipfixcol2 -L -v
